# Generated by Django 3.1.1 on 2020-12-10 21:28

from django.db import migrations


def insert_data(apps, schema_editor):
    Course = apps.get_model("accounts", "Course")
    Course.objects.bulk_create([
        Course(name='BS Psychology'),
        Course(name='AB Communication'),
        Course(name='AB English Language'),
        Course(name='BS Biology'),
        Course(name='BS Mathematics'),
        Course(name='Bachelor of Elementary Education'),
        Course(name='Bachelor of Secondary Education Major in English'),
        Course(name='Bachelor of Secondary Education Major in Filipino'),
        Course(name='Bachelor of Secondary Education Major in Mathematics'),
        Course(name='Bachelor of Secondary Education Major in Science'),
        Course(name='Bachelor of Multimedia Arts'),
        Course(name='BS Computer Science'),
        Course(name='BS Information Technology'),
        Course(name='ARCH'),
        Course(name='CE'),
        Course(name='CHE'),
        Course(name='CPE'),
        Course(name='ECE'),
        Course(name='EE'),
        Course(name='EM'),
        Course(name='IE'),
        Course(name='BS Mechanical Engineering'),
        Course(name='BS Mechanical Engineering with Mechatronics'),
        Course(name='BS Accountancy'),
        Course(name='BS Management Accounting'),
        Course(name='BS Accounting Information Systems'),
        Course(name='BS Hospitality Management'),
        Course(name='BS Tourism Management'),
        Course(name='Bachelor in Public Administration'),
        Course(name='BS Office Administration'),
        Course(name='BS Business Administration Major in Banking and Financial Management'),
        Course(name='BS Business Administration Major in Business Analytics'),
        Course(name='BS Business Administration Major in General Business Management'),
        Course(name='BS Business Administration Major in Human Resource Management'),
        Course(name='BS Business Administration Major in Marketing Management'),
        Course(name='BS Business Administration Major in Operations Management'),
        Course(name='BS Business Administration Major in Quality Management'),
        Course(name='Nursing'),
        Course(name='Others'),
    ])


def delete_data(apps, schema_editor):
    Course = apps.get_model('accounts', 'Course')
    Course.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201211_0528'),
    ]

    operations = [
        migrations.RunPython(insert_data, delete_data)
    ]
